### ISSUE TITLE
Icons of the LSP symbols are not being shown

### ISSUE THREAD

**Issue by samebchase** [emacs-lsp/lsp-treemacs#159]
Hi,

I love the symbols list. It's helping me a lot while reading and writing code.

It seems this change, https://github.com/emacs-lsp/lsp-treemacs/commit/323b4c9790f8f48c6dbce65d31dd969d1f55df49 introduces the issue. When I changed `-if-let` back to `if-let` the icons are visible again.

![Screenshot from 2023-06-30 15-35-41](https://github.com/emacs-lsp/lsp-treemacs/assets/166555/c10927ce-d66b-453f-aa2e-610abd416cbd)

**Comment by samebchase** [comment]
Submitted a PR for this: https://github.com/emacs-lsp/lsp-treemacs/pull/160

Thanks once again, for all your efforts! :pray:

**Comment by pobermei** [comment]
> Submitted a PR for this: #160
> 
> Thanks once again, for all your efforts! 🙏

@samebchase It appears that #160 is erroneously removing unneeded parentheses from the [incorrect line 236](https://github.com/emacs-lsp/lsp-treemacs/pull/160/files#diff-d3f0ff3960ac2ef27f5299209fc76727ff36e5d197a4308ec33b1c62f11ad15b), rather than from [line 89](https://github.com/emacs-lsp/lsp-treemacs/blob/7011f3cae30d311a7d123ecd338e7abff2550fa6/lsp-treemacs-generic.el#L89) as you pointed out [above](https://github.com/emacs-lsp/lsp-treemacs/issues/159#issue-1782266408).

**Comment by samebchase** [comment]
@pobermei My bad, that's a great catch! Let me fix it and send a new PR.

**Comment by samebchase** [comment]
Raised a new PR https://github.com/emacs-lsp/lsp-treemacs/pull/161
